apiVersion: v2
name: openpanel
description: A Helm chart for OpenPanel analytics platform
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - analytics
  - openpanel
  - monitoring
maintainers:
  - name: OpenPanel Team
